[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "garner"
authors = [
  { name="Justin McGuire", email="jm@landedstar.com" },
]
dynamic = ["version"]
description = "Look up words in the Garner Usage Dictionary from the command-line."
readme = "README.md"
requires-python = ">=3.9"
license = {file = "LICENSE"}
dependencies = [
    "jellyfish>=1.2,<2",
    "rich>=15,<16",
]
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]

[project.optional-dependencies]
release = [
    "build>=1.2",
]

[project.urls]
Homepage = "https://github.com/jmcguire/garner"

[project.scripts]
garner = "garner.cli:main"

[tool.setuptools.dynamic]
version = {attr = "garner.__version__.__version__"}

[tool.setuptools.packages.find]
include = ["garner*"]

[tool.setuptools.package-data]
"garner.data" = ["dictionary.sqlite"]
