[build-system]
requires = ["setuptools>=77.0.3", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "garner"
dynamic = ["version"]
description = "Command-line Garner Usage Dictionary"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "jellyfish>=1.2,<2",
    "rich>=15,<16",
]
classifiers = [
    "Environment :: Console",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
]

[project.optional-dependencies]
release = [
    "build>=1.2",
]

[project.scripts]
garner = "garner.cli:main"

[tool.setuptools.dynamic]
version = {attr = "garner.__version__.__version__"}

[tool.setuptools.packages.find]
include = ["garner*"]

[tool.setuptools.package-data]
"garner.data" = ["dictionary.sqlite"]
